[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "wordops-provisioner"
version = "0.0.1"
description = "Python tool for provisioning WordPress sites using WordOps"
readme = "README.md"
requires-python = ">=3.11"
license = { text = "MIT" }

dependencies = [
  "paramiko",
  "python-dotenv",
]

[project.optional-dependencies]
dev = [
  "black",
  "mypy",
  "pytest",
  "ruff",
]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]

[tool.mypy]
strict = true

[[tool.mypy.overrides]]
module = "tests.*"
disallow_untyped_defs = false
