CREATE TABLE IF NOT EXISTS `tracking_pageviews` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `view_id` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `pageview_date` date NOT NULL,
  `url` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `domain` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `referrer` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `ip` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `user_agent` text CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci,
  `language` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `timezone` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `viewport_width` int DEFAULT NULL,
  `viewport_height` int DEFAULT NULL,
  `ts_pageview_ms` bigint unsigned DEFAULT NULL,
  `ts_metrics_ms` bigint unsigned DEFAULT NULL,
  `ttfb_ms` double DEFAULT NULL,
  `dom_content_loaded_ms` double DEFAULT NULL,
  `load_event_end_ms` double DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `processed_at` timestamp NULL DEFAULT NULL,
  `processed_status` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tracking_pageviews_view_id_unique` (`view_id`),
  KEY `tracking_pageviews_pageview_date_domain_index` (`pageview_date`,`domain`),
  KEY `tracking_pageviews_domain_pageview_date_index` (`domain`,`pageview_date`),
  KEY `tracking_pageviews_pageview_date_index` (`pageview_date`),
  KEY `tracking_pageviews_domain_index` (`domain`),
  KEY `tracking_pageviews_language_index` (`language`),
  KEY `tracking_pageviews_timezone_index` (`timezone`),
  KEY `tracking_pageviews_ttfb_ms_index` (`ttfb_ms`),
  KEY `tracking_pageviews_dom_content_loaded_ms_index` (`dom_content_loaded_ms`),
  KEY `tracking_pageviews_load_event_end_ms_index` (`load_event_end_ms`),
  KEY `tracking_pageviews_processed_at_index` (`processed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
