CREATE TABLE IF NOT EXISTS `tracking_pageviews_daily` (
  `id` bigint unsigned NOT NULL AUTO_INCREMENT,
  `pageview_date` date NOT NULL,
  `domain` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL,
  `is_internal` tinyint(1) NOT NULL,
  `category` varchar(255) CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'none',
  `pageviews` int NOT NULL DEFAULT '0',
  `googlebot_ua_pageviews` int NOT NULL DEFAULT '0',
  `googlebot_ip_pageviews` int NOT NULL DEFAULT '0',
  `google_ip_pageviews` int NOT NULL DEFAULT '0',
  `bingbot_ua_pageviews` int NOT NULL DEFAULT '0',
  `bingbot_ip_pageviews` int NOT NULL DEFAULT '0',
  `microsoft_ip_pageviews` int NOT NULL DEFAULT '0',
  `cnt_pageviews_with_metrics` int NOT NULL DEFAULT '0',
  `avg_ttfb_ms` double DEFAULT NULL,
  `median_ttfb_ms` double DEFAULT NULL,
  `p95_ttfb_ms` double DEFAULT NULL,
  `avg_dom_content_loaded_ms` double DEFAULT NULL,
  `median_dom_content_loaded_ms` double DEFAULT NULL,
  `p95_dom_content_loaded_ms` double DEFAULT NULL,
  `avg_load_event_end_ms` double DEFAULT NULL,
  `median_load_event_end_ms` double DEFAULT NULL,
  `p95_load_event_end_ms` double DEFAULT NULL,
  `created_at` timestamp NULL DEFAULT NULL,
  `updated_at` timestamp NULL DEFAULT NULL,
  `processed_at` timestamp NULL DEFAULT NULL,
  `processed_status` json DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE KEY `tpv_pageview_date_domain_is_internal_category_unique` (`pageview_date`,`domain`,`is_internal`,`category`),
  KEY `tracking_pageviews_daily_pageview_date_index` (`pageview_date`),
  KEY `tracking_pageviews_daily_domain_index` (`domain`),
  KEY `tracking_pageviews_daily_is_internal_index` (`is_internal`),
  KEY `tracking_pageviews_daily_category_index` (`category`),
  KEY `tracking_pageviews_daily_pageviews_index` (`pageviews`),
  KEY `tracking_pageviews_daily_googlebot_ua_pageviews_index` (`googlebot_ua_pageviews`),
  KEY `tracking_pageviews_daily_googlebot_ip_pageviews_index` (`googlebot_ip_pageviews`),
  KEY `tracking_pageviews_daily_google_ip_pageviews_index` (`google_ip_pageviews`),
  KEY `tracking_pageviews_daily_bingbot_ua_pageviews_index` (`bingbot_ua_pageviews`),
  KEY `tracking_pageviews_daily_bingbot_ip_pageviews_index` (`bingbot_ip_pageviews`),
  KEY `tracking_pageviews_daily_microsoft_ip_pageviews_index` (`microsoft_ip_pageviews`),
  KEY `tracking_pageviews_daily_cnt_pageviews_with_metrics_index` (`cnt_pageviews_with_metrics`),
  KEY `tracking_pageviews_daily_avg_ttfb_ms_index` (`avg_ttfb_ms`),
  KEY `tracking_pageviews_daily_median_ttfb_ms_index` (`median_ttfb_ms`),
  KEY `tracking_pageviews_daily_p95_ttfb_ms_index` (`p95_ttfb_ms`),
  KEY `tracking_pageviews_daily_avg_dom_content_loaded_ms_index` (`avg_dom_content_loaded_ms`),
  KEY `tracking_pageviews_daily_median_dom_content_loaded_ms_index` (`median_dom_content_loaded_ms`),
  KEY `tracking_pageviews_daily_p95_dom_content_loaded_ms_index` (`p95_dom_content_loaded_ms`),
  KEY `tracking_pageviews_daily_avg_load_event_end_ms_index` (`avg_load_event_end_ms`),
  KEY `tracking_pageviews_daily_median_load_event_end_ms_index` (`median_load_event_end_ms`),
  KEY `tracking_pageviews_daily_p95_load_event_end_ms_index` (`p95_load_event_end_ms`),
  KEY `tracking_pageviews_daily_processed_at_index` (`processed_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
