[themes]
ananke        = "https://github.com/theNewDynamic/gohugo-theme-ananke.git"
beautifulhugo = "https://github.com/halogenica/beautifulhugo.git"
clarity       = "https://github.com/chipzoller/hugo-clarity.git"
mainroad      = "https://github.com/Vimux/Mainroad.git"
paper         = "https://github.com/nanxiaobei/hugo-paper.git"
papermod      = "https://github.com/adityatelange/hugo-PaperMod.git"
terminal      = "https://github.com/panr/hugo-theme-terminal.git"